---
- name: Initial setup VM
  hosts: dedic
  vars_files:
    - vms.yml
  tasks:
    - name: Clone VMs
      proxmox_kvm:
        node: "{{ node }}"
        name: "{{ item.value.name }}"
        newid: "{{ item.value.vmid }}"
        api_user: "{{ api_user }}"
        api_password: "{{ api_password }}"
        api_host: "{{ api_host }}"
        clone: "{{ clone_vm }}"
        full: yes
      loop: "{{ lookup('dict', vms) }}"

    - name: Set IP addresses
      command: "qm set {{ item.value.vmid }}  --ipconfig0 ip={{ item.value.ipaddress }},gw={{ item.value.gateway }}"
      loop: "{{ lookup('dict', vms) }}"

    - name: Store SSH keys temporarily
      copy:
        src: "{{ ssh_keys_dir }}/"
        dest: "{{ temp_keys_dir }}"

    - name: Set SSH keys
      command: "qm set {{ item.value.vmid }} --sshkey {{ temp_keys_dir }}/id_rsa.pub"
      loop: "{{ lookup('dict', vms) }}"

    - name: Delete temporary SSH keys directory
      file:
        path: "{{ temp_keys_dir }}"
        state: absent

    - name: Update VMs
      proxmox_kvm:
        api_host:     "{{ api_host }}"
        api_user:     "{{ api_user }}"
        api_password: "{{ api_password }}"
        cores:        "{{ item.value.cores }}"
        sockets:      "{{ item.value.sockets }}"
        memory:       "{{ item.value.memory }}"
        update:       yes
        vmid:         "{{ item.value.vmid }}"
        node:         "{{ node }}"
        name:         "{{ item.value.name }}"
      loop: "{{ lookup('dict', vms) }}"

    - name: Start VMs
      proxmox_kvm:
        api_host:     "{{ api_host }}"
        api_password: "{{ api_password }}"
        api_user:     "{{ api_user }}"
        vmid:         "{{ item.value.vmid }}"
        node:         "{{ node }}"
        state:        started
      loop: "{{ lookup('dict', vms) }}"
