apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-by-header: "greenfield"
    nginx.ingress.kubernetes.io/canary-by-header-value: "true"
  name: test-rest-canary
spec:
  rules:
    - host: ingress.example.com
      http:
        paths:
          - backend:
              serviceName: test-rest-svc-new
              servicePort: 80
            path: /test
